bp_admin:
    resource: "@BpAdminBundle/Controller/"
    type:     annotation
    prefix:   /

bp_cart:
    resource: "@BpCartBundle/Controller/"
    type:     annotation
    prefix:   /

bp_payment:
    resource: "@BpPaymentBundle/Controller/"
    type:     annotation
    prefix:   /

bp_product:
    resource: "@BpProductBundle/Controller/"
    type:     annotation
    prefix:   /

bp_profile:
    resource: "@BpProfileBundle/Controller/"
    type:     annotation
    prefix:   /

bp_core:
    resource: "@BpCoreBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

stripe_payment_routes:
    resource: .
    type: stripe