services:
    cart:
        class:        Bp\CartBundle\Services\CartService
        arguments:    [@session,@doctrine,%cart.tva%]
    contract:
        class:        Bp\CartBundle\Services\ContractService
        arguments:    [@doctrine,@cart,@reference.generator]
    reference.generator:
        class:        Bp\CartBundle\Services\ReferenceGenerator
        arguments:    [@doctrine]