<?php

namespace Bp\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomPackRepository extends EntityRepository
{
    public function findOneLikeRef($ref)
     {
         return $this->getEntityManager()
             ->createQuery('SELECT p FROM BpProductBundle:CustomPack p
           
                             WHERE p.reference LIKE :ref
                        ')
             ->setParameters(array(
                 'ref' => "%$ref%"
             ))
             ->getResult();
     }
}
