<?php

namespace Bp\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Bp\ProductBundle\Entity\Product;
/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends EntityRepository
{
    public function getStockedObjByProduct($number, Product $product)
    {

    return $this->getEntityManager()
        ->createQuery('SELECT o FROM BpProductBundle:Object o
                        WHERE o.product = :product 
                        AND o.status = :status
                   ')
        ->setParameters(array(
            'product' => $product->getId(),
            'status' => 'en stock'
        ))
        ->setMaxResults($number)
        ->getResult();
    }
}
